### ISSUE TITLE
Current track controls

### ISSUE THREAD

**Issue by rocketinventor** [FellowHead/flpjck#3]
Hello!

Sometimes (for various reasons), it is desirable to pause the batch operation (i.e. to not be bombarded by FL repeatedly opening up). Other times, there might be a desire to halt or postpone the rendering of a track (i.e. to fix an issue where there is an infinite loop in the rendering). It would be nice, therefore, if there were controls inside the app UI for pausing/resuming the operation, and also for controlling the current track (like described above).

**Comment by doodle-alt** [comment]
Hey there! A [function to pause](https://github.com/FellowHead/FlpJck/commit/2669e95b8ba71f8079929f36f3d8161c0264b319) is now fully implemented, as well as the option to quickly edit a project in Fruity Loops via context menu. Happy rendering!
