### ISSUE TITLE
Hang on render

### ISSUE THREAD

**Issue by rocketinventor** [FellowHead/flpjck#4]
Sometimes Fl Studio can be prevented from successfully finishing the render of a track. Possible reasons for this can include time markers that tell FL Studio to skip or pause, and also missing/demo plugins and samples. In the case of an infinite loop, the chunk number will count upward to a certain point until it reaches the loop, in which case, the number just goes back down and starts again. This result of this is that a small number of files, that should be manageable and finish quickly will take an indefinite amount of time to finish (several hours or until the "abort" action is done).

Possible solutions:
- Allow the user to set a time limit on the FL rendering process (i.e. one hour)
- Use another library to inspect and modify the .flp files to find and fix possible errors
- Monitor the window title of FL Studio to tell if the rendering is being blocked or looped (did it get to "Rendering: X/Y", yet? did the number start over?).
- Use robot.js to check for errors, dialogs, etc. that can stall the process

**Comment by doodle-alt** [comment]
Alright, interesting. I'll notify Image Line about the weird skip marker behavior, as this also happens when rendering manually.

Regarding demo plugins and other warning messages, I think electronjs can handle screen-grabbing (doesn't even need robot.js, so that's a win). A timeout also seems nice.

I didn't notice FL's window title changes. That just sparked some ideas, too!

Extracting the actual .flp files seems a bit too hacky and risky, because Image Line probably doesn't want users to reverse engineer their products.

Thank you for the suggestions. I'll try some things!

**Comment by doodle-alt** [comment]
So, a [timeout](https://github.com/FellowHead/FlpJck/commit/5fc19811bd9370699df5af1b6a0c8d7c1b9be9cd#diff-e6a92a9bd7f0b3ff7594bd7c55b70bcfR18-R23) for warning messages has been implemented. It's set to 2 minutes by default.
Maybe I'll add some user interface for adjustment in the future.

**Comment by doodle-alt** [comment]
There now is [another timeout for maximum render duration](https://github.com/FellowHead/FlpJck/commit/460273fe4838ff903cde027d623a48c05b624b1f#diff-e6a92a9bd7f0b3ff7594bd7c55b70bcfR25-R32), set to 45 minutes by default.

Also, [a small workaround](https://github.com/FellowHead/FlpJck/commit/9fc708c97c0d934ac9e744352af815efdfdbb7be) handling looping skip markers.

As soon as I confirm those changes on MacOS, I'll declare this solved.

**Comment by rocketinventor** [comment]
Nice work! Is there a way, though, to automatically click through the pop-ups so that they close? Pre-processing of the file could also accomplish this (in a fairly reliable way). Parsing/modifying an .flp file does not constitute as "reverse-engineering" a program. It is just a bunch of information on what you did inside your project (stored in binary format). There are already libraries to do this. This is no different than using a library to modify a Word document because it won't open. 

Here is a Node.js library for working with .flp’s: https://github.com/b15h0y/flp-parser, and here is a C++/ .Net Library based on the node.js library (but with better documentation) https://github.com/monadgroup/FLParser.

I’ll have to try out these changes sometime, but as of now, I am all rendered up 😉
BTW, if a file gets aborted, canceled, or has some other issue, does this information get stored anywhere? It should.

**Comment by doodle-alt** [comment]
Well, why'd you ever like to listen to a song with missing samples or even missing instruments? It's just that I don't really get the functionality here.

The success of a render is, in a way, stored: if a timer runs out, FL Studio gets terminated and no new render information is associated with the flp. That means, the file is still marked as "new" (rendered file is out of date) and therefore colored green.
I couldn't yet find an easy way to determine if the user clicked "Abort" in FL Studio, so these projects are still being falsely registered as rendered. I'll get to that sometime.

Anyway, timeout and window title reading works on MacOS now (must ask permission first, sadly).

**Comment by doodle-alt** [comment]
Hey there, just wanted to say that the skip marker bug has been resolved in FL Studio 20.7.3, as mentioned in [its changelog](https://www.image-line.com/history/):
> Bug fixes:
> [...]
> 9377 Audio export freezes when using skip markers
